rules:
  # OAuth Token Endpoint
  - path: /oauth/token
    methods: ['POST']
    query_params:
      grant_type: client_credentials
      client_id: qwerty      
      client_secret: eweqweqwqew 
    request_headers:
      Content-Type: ["application/x-www-form-urlencoded"]
    responses:
      - status_code: 200
        headers:
          Content-Type: ["application/json"]
        body: |
          {
            "access_token": "xxxxxxxxxxxxx",
            "expires_in": 3600,
            "token_type": "Bearer"
          }

  # Search Events Endpoint initial
  - path: /v2024/search/events
    methods: ["POST"]
    request_headers:
      Authorization: ["Bearer xxxxxxxxxxxxx"]
      Content-Type: ["application/json"]
    request_body: /^\{"query":\{"query":"\*"\},"queryResultFilter":\{\},"queryType":"SAILPOINT","searchAfter":\["[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z"\],"sort":\["created"\]\}/
    query_params:
      limit: "2"
    responses:
      - status_code: 200
        headers:
          Content-Type: ["application/json"]
        body: |
          [
            {
              "created": "2024-12-12T19:41:24.121Z",
              "id": "cb2fc359e6b31aad1fdc2d290e5279a71cf747eda0221d8f46e1f775bba21c89",
              "action": "AUTHENTICATION-103",
              "type": "AUTH",
              "actor": { "name": "test.user" },
              "_type": "event"
            },
            {
              "created": "2024-12-12T19:41:24.124Z",
              "id": "a99320b19b034ae1b68181754b5df214",
              "action": "IDENTITY_PROCESSING",
              "type": "IDENTITY_PROCESSING",
              "actor": { "name": "slpt.support" },
              "_type": "event"
            }
          ]
  # Search Events Endpoint 1st pagination
  - path: /v2024/search/events
    methods: ["POST"]
    request_headers:
      Authorization: ["Bearer xxxxxxxxxxxxx"]
      Content-Type: ["application/json"]
    request_body: /^\{"query":\{"query":"\*"\},"queryResultFilter":\{\},"queryType":"SAILPOINT","searchAfter":\["2024-12-12T19:41:24\.124Z"\],"sort":\["created"\]\}/
    query_params:
      limit: "2"
    responses:
      - status_code: 200
        headers:
          Content-Type: ["application/json"]
        body: |
          [
            {
              "created": "2024-12-13T20:41:24.121Z",
              "id": "cb2fc359e6b31aad1fdc2d290e5279a71cf747eda0221d8f46e1f775bba21c77",
              "action": "AUTHENTICATION-103",
              "type": "AUTH",
              "actor": { "name": "test.user" },
              "_type": "event"
            }
          ]          


  # Search Events Endpoint 2nd pagination and should stop here
  - path: /v2024/search/events
    methods: ["POST"]
    request_headers:
      Authorization: ["Bearer xxxxxxxxxxxxx"]
      Content-Type: ["application/json"]
    request_body: /^\{"query":\{"query":"\*"\},"queryResultFilter":\{\},"queryType":"SAILPOINT","searchAfter":\["2024-12-13T20:41:24\.121Z"\],"sort":\["created"\]\}/
    query_params:
      limit: "2"
    responses:
      - status_code: 200
        headers:
          Content-Type: ["application/json"]
        body: |
          []           